import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/navbar';
import { Dock } from '@/components/Common/FloatingDock';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Marauder's Map",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body className={inter.className}>
        <NavBar organisationName="Monash" />
        {children}
        <Dock />
      </body>
    </html>
  );
}
